server:
  port: ${PORT:9090}
#logging:
#  level:
#    io:
#      jsonwebtoken: DEBUG
#    org:
#      springframework:
#        security: DEBUG
debug: true
spring:
  application:
    name: User-Authentication
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: ${SECRET_KEY}